// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbkuvzrvdypctdauiedu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNia3V2enJ2ZHlwY3RkYXVpZWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Nzc5MjAsImV4cCI6MjA2NjU1MzkyMH0.kpyU99R6xOxsJdm_7tP93wfRPlX7eq7oSZbh6TqkQiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);